# Generated by Django 5.2.4 on 2025-07-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hike',
            name='duration_days',
        ),
        migrations.AddField(
            model_name='hike',
            name='duration_hours',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='hike',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='hike',
            name='difficulty',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hike',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
